name: Install Dependencies and Test Angular Application
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      #   run: |
      #     echo "Cloning the repository..."
      #     echo "Repository URL:{{toJson(github)}}"
      #     git clone https://github.com/visit2shobhit/Angular.git angularrepo
      #     cd angularrepo && ls
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install Angular CLI globally
        run: |
          echo "Install Angular CLI globally..."
          npm install -g @angular/cli    
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Angular application
        run: |
          echo "Installing dependencies..."
          ng build --configuration production
          echo "Build completed successfully."


